name: PR Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 9.15.2

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm ci:test:unit
